CREATE TABLE ENTITYLOOKUP
(
	ENTITYLOOKUPID INT PRIMARY KEY IDENTITY(1, 1)
	, CATEGORY VARCHAR(100)
	, LOOKUPVALUE VARCHAR(100)
	, DISPLAYORDER INT
)
GO

INSERT INTO ENTITYLOOKUP(CATEGORY, LOOKUPVALUE, DISPLAYORDER)
SELECT 'State', 'Andhra Pradesh', 1 UNION ALL
SELECT 'State', 'Telangana', 2 UNION ALL
SELECT 'State', 'TO-DO ADD MORE STATES', 1 UNION ALL
--SELECT 'FINYEAR', '2020~2021', 1 UNION ALL
--SELECT 'FINYEAR', '2021~2022', 2 UNION ALL
--SELECT 'FINYEAR', '2022~2023', 3 UNION ALL
SELECT 'METHODOFACCOUNTING', 'Mercentile', 1 UNION ALL
SELECT 'METHODOFACCOUNTING', 'Cash', 2 UNION ALL
SELECT 'CURRENCY', 'INR', 1 UNION ALL
SELECT 'CURRENCY', 'USD', 2 UNION ALL
SELECT 'RESIDENT STATUS', 'Resident', 1 UNION ALL
SELECT 'RESIDENT STATUS', 'Non Resident', 2 UNION ALL
SELECT 'RESIDENT STATUS', 'Not Ordinarily Resident', 3 UNION ALL
SELECT 'ENTITYTYPE', 'Individual Entity', 1 UNION ALL
SELECT 'ENTITYTYPE', 'Firm', 2 UNION ALL
SELECT 'ENTITYTYPE', 'Company', 3 UNION ALL
SELECT 'ENTITYTYPE', 'AOP BOI', 4
GO


--CREATE TABLE STATEINFO
--(
--	STATEID INT PRIMARY KEY IDENTITY(1, 1)
--	, STATENAME VARCHAR(100)
--)
--GO

--CREATE TABLE FINYEARLIST
--(
--	FINYEARID INT PRIMARY KEY IDENTITY(1, 1)
--	, FINYEAR VARCHAR(20)
--)
--GO

CREATE TABLE ADDRESSINFO
(
	ADDRESSID INT PRIMARY KEY IDENTITY(1, 1)
	, HNO VARCHAR(100)
	, LANDMARK VARCHAR(200)
	, DISTRICT VARCHAR(50)
	, STATEID INT FOREIGN KEY REFERENCES ENTITYLOOKUP (ENTITYLOOKUPID)
	, PINCODE VARCHAR(10)
)
GO


CREATE TABLE ENTITY
(
	ENTITYID INT IDENTITY(1, 1) PRIMARY KEY
	, ENTITYNAME VARCHAR(100)
	, ENTITYTYPEID INT FOREIGN KEY REFERENCES ENTITYLOOKUP (ENTITYLOOKUPID)
	, NOOFPARTNERS INT
)
GO

CREATE TABLE PERSON
(
	PERSONID INT PRIMARY KEY IDENTITY(1, 1)
	, PERSONNAME VARCHAR(100)
	, FATHERNAME VARCHAR(100)
	, PANNUMBER VARCHAR(11)
	, AADHARNUMBER VARCHAR(12)
	, MOBILENUMBER VARCHAR(10)
	, OFFICENUMBER VARCHAR(10)
	, PERMANENTADDRESSID INT FOREIGN KEY REFERENCES ADDRESSINFO (ADDRESSID)
	, BUSINESSADDRESSID INT FOREIGN KEY REFERENCES ADDRESSINFO (ADDRESSID)
	, EMAILID VARCHAR(50)
	, FINYEARID INT FOREIGN KEY REFERENCES ENTITYLOOKUP (ENTITYLOOKUPID)
	, METHOFACCID INT FOREIGN KEY REFERENCES ENTITYLOOKUP (ENTITYLOOKUPID)
	, CURRENCYID INT FOREIGN KEY REFERENCES ENTITYLOOKUP (ENTITYLOOKUPID)
	, RESIDENTSTATUSID INT FOREIGN KEY REFERENCES ENTITYLOOKUP (ENTITYLOOKUPID)
	, ENTITYID INT FOREIGN KEY REFERENCES ENTITY (ENTITYID)
	, DINNO VARCHAR(50)
	, ISAUTHORIZEDSIGNATORY BIT
	, PERCENTAGESHARES DECIMAL(5, 2)
	, NOOFSHARES DECIMAL(12, 2)
)
GO
	
CREATE TABLE GSTREGNO
(
	GSTREGNOID INT PRIMARY KEY IDENTITY(1, 1)
	, PERSONID INT FOREIGN KEY REFERENCES PERSON (PERSONID)
	, STATEID INT FOREIGN KEY REFERENCES ENTITYLOOKUP (ENTITYLOOKUPID)
	, GSTNO VARCHAR(20)
)
GO


ALTER TABLE ENTITY ADD PERSONID INT FOREIGN KEY REFERENCES PERSON (PERSONID)
GO

ALTER TABLE PERSON ADD PRIMARYGSTNOID INT FOREIGN KEY REFERENCES GSTREGNO (GSTREGNOID)
GO


--SELECT * FROM ENTITYLOOKUP